# Generated by Django 5.2.11 on 2026-03-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_option',
            new_name='delivery_option_id',
        ),
    ]
