# Generated by Django 5.2.11 on 2026-03-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_delivery_option_order_delivery_option_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_option_id',
            new_name='delivery_option',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default=''),
        ),
    ]
