# Generated by Django 5.2.11 on 2026-03-17 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_delivery_option_id_order_delivery_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoption',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
    ]
