# Generated by Django 5.2.11 on 2026-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("register", "register"),
                            ("change_email", "change_email"),
                            ("change_phone", "change_phone"),
                            ("change_password", "change_password"),
                        ],
                        max_length=32,
                    ),
                ),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="SMSCode",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="emailcode",
            index=models.Index(
                fields=["email", "purpose", "created_at"],
                name="accounts_em_email_c7f6f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailcode",
            index=models.Index(
                fields=["email", "purpose", "code"], name="accounts_em_email_b59ce6_idx"
            ),
        ),
    ]
