# Generated by Django 5.2.11 on 2026-02-22 15:38

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_emailcode_delete_smscode_alter_user_phone_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(("email__isnull", False)),
                name="accounts_user_email_ci_unique",
            ),
        ),
    ]
