# Generated by Django 5.2.12 on 2026-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_seed_default_user_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcode",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "register"),
                    ("change_email", "change_email"),
                    ("change_password", "change_password"),
                ],
                max_length=32,
            ),
        ),
    ]
