# Generated by Django 5.2.11 on 2026-03-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_emailcode_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='purpose',
            field=models.CharField(choices=[('register', 'register'), ('change_email', 'change_email'), ('change_password', 'change_password'), ('reset_password', 'reset_password')], max_length=32),
        ),
    ]
